//
//  Problem2.m
//  Euler
//
//  Created by Jacob Farkas on 1/10/08.
//  Copyright 2008 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "PEProblem.h"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed one million.
*/

@interface Problem2 : PEProblem {
}
@end

@implementation Problem2
- (NSString *) runSolution
{
    int last = 1;
    int cur = 1;
    int tmp;
    int sum = 0;
    while (cur < 1000000) {
        if (self.verbose) printf("%d ", cur);
        if (cur % 2 == 0) sum += cur;
        tmp = cur;
        cur = cur + last;
        last = tmp;
    }
    return [NSString stringWithFormat:@"%d", sum];
}

- (NSString *) realAnswer { return @"1089154"; }
@end
